# Generated by Django 5.0.1 on 2024-03-05 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Model_Class',
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Subtopic',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='ModelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('is_show', models.BooleanField(default=True)),
                ('model_class', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.modelclass')),
            ],
            options={
                'db_table': 'Model_Details',
            },
        ),
        migrations.AddField(
            model_name='modelclass',
            name='sub_topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.subtopic'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.topic'),
        ),
    ]
