# Generated by Django 5.0.1 on 2024-03-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayerLabel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclass',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.subtopic'),
        ),
        migrations.AlterField(
            model_name='modeldetails',
            name='model_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.modelclass'),
        ),
        migrations.AlterField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='LayerLabel.topic'),
        ),
    ]
