# Generated by Django 5.0.1 on 2024-03-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LayerLabel', '0002_alter_modelclass_sub_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMappingUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField()),
                ('layer_id', models.IntegerField()),
                ('api_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Model_Mapping_Urls',
            },
        ),
    ]
