# Generated by Django 5.0.1 on 2024-02-17 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField()),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Member',
            },
        ),
        migrations.CreateModel(
            name='MemberPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField()),
                ('admin', models.BooleanField()),
                ('member_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'db_table': 'Member_Permission',
            },
        ),
    ]
