# Generated by Django 5.0.1 on 2024-02-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberpermission',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memberpermission',
            name='read_only',
            field=models.BooleanField(default=True),
        ),
    ]
